### ISSUE TITLE
Error AbortController is not defined

### ISSUE THREAD

**Issue by vasa-develop** [ipfs-shipyard/peer-pad#225] opened 2018-11-04 13:48 UTC
Just checked out peerpad website. But after sharing the link and opening the link in a new window, the windows don't seem to sync?  Also, my status is always offline...what is the status here(tried it with the local ipfs daemon, but it still shows offline)?

Can someone tell me what am I missing here?

**Comment by pgte** [comment] 2018-11-04 15:42
I could not reproduce this: I'm able to get online and sync between two browsers.
Is there any error in the console?

**Comment by vasa-develop** [comment] 2018-11-05 17:08
Here are the console logs(using the local ipfs daemon):
https://gateway.ipfs.io/ipfs/QmexQFGzCQVAF7mmLBsTHnq6rK6SBAhAfNEY6TjftDFhTz

If you don't mind, can you make a small screen video to show simple steps on how to use it via the website(using it by sharing the link) ...I know it sounds dumb, but I can't figure out what am I missing here.

**Comment by akhil0101** [comment] 2018-11-11 09:55
Just checked out peerpad website. But after sharing the link and opening the link in a new window, the windows don't seem to sync? Also, my status is always offline...what is the status here(tried it with the local ipfs daemon, but it still shows offline)?

i am also facing the same problem can u rectify the problem

**Comment by vasa-develop** [comment] 2018-11-13 18:48
Still facing the same problem.

**Comment by victorb** [comment] 2018-11-18 16:19
Thanks @vasa-develop for sharing the console.log output, very helpful! @akhil0101 could you do the same so we can see if it's the same issue for you?

Regarding @vasa-develop's issue, seems you're using a browser where `AbortController` is not defined. According to https://caniuse.com/#search=AbortController, it should be supported in the latest browsers (minus any version of IE). Which browser are you using?

@alanshaw according to the stacktraces, this error comes from AbortController being used in the preload-browser. Is it possible we can either shim it or similar since preloading is kind of an optional feature?

```
 File ../node_modules/ipfs/src/core/runtime/preload-browser.js line 12 col 1 in e
const controller = new AbortController()
```

**Comment by vasa-develop** [comment] 2018-11-19 05:58
@victorb  Thanks for replying. My browser specifications are as follows:

**Chrome: Version 64.0.3282.140 (Official Build) (64-bit)**
(This shows the error that I linked above. Seems like it AbortController is not defined in this version)

But it shows **no error logs on Mozilla 63.0 (64-bit)**. The window shows that I am online. But when I tried sharing the document(tried both, read and write), the changes on one window doesn't show up on the other window.

**P.S. I am on Ubuntu 16.04 LTS**

If you want to know anything more about the logs or what environment using, feel free to ask.

**Comment by alanshaw** [comment] 2018-11-19 09:01
@vasa-develop are you able to upgrade your chrome browser to version 66 or higher and test?

**Comment by vasa-develop** [comment] 2018-11-19 13:37
@alanshaw  I will upgrade it and get back to you.

**Comment by victorb** [comment] 2018-11-19 20:20
> But it shows no error logs on Mozilla 63.0 (64-bit). The window shows that I am online. But when I tried sharing the document(tried both, read and write), the changes on one window doesn't show up on the other window.

This might be a issue where the same Peer ID is being used, because it's essentially the same browser session but another tab, and I think PeerPad is reusing the same Peer ID, leading to pubsub not working correctly. @pgte correct me if I'm wrong about this.

@vasa-develop could you try to open the same pad but in two different browsers where PeerPad shows the status as online? For example, try opening it up in Firefox and Chrome with both windows being side-by-side (Chrome throttles the JS if it's in the background)

**Comment by vasa-develop** [comment] 2018-11-20 18:37
@victorb Just checked it out. It works when I use 2 different browsers.

**Comment by victorb** [comment] 2018-11-21 00:21
@vasa-develop great! Renamed the title so it'll be easier to find in the future, and let's close this one.

 @akhil0101 if it turns out you have a different issue than "AbortController is not defined", please open a new issue with more details of the problem, including javascript console logs if possible.

**Closed by victorb** 2018-11-21 00:21 UTC
